<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Course;
use App\Models\CourseNote;
use App\Models\CourseSubject;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

// One-off seeder that inserts the 20 doc-spec sample courses (generated by
// the scratchpad gen_courses_data.php script) with their Subject -> Chapter
// (PDF note) structure. Additive only — does not touch any existing course,
// category, subject, or note row.
class DocCourseSeeder extends Seeder
{
    public function run(): void
    {
        $genDir = 'C:/Users/pc/AppData/Local/Temp/claude/C--xampp-htdocs-lawstudents/563a7de3-741a-46a7-b5d5-a67237216397/scratchpad/course_seed/gen';
        $manifest = json_decode(file_get_contents("$genDir/manifest.json"), true);

        $coursesCreated = 0;
        $subjectsCreated = 0;
        $chaptersCreated = 0;

        foreach ($manifest as $entry) {
            $category = Category::where('slug', $entry['category_slug'])->first();
            if (!$category) {
                $this->command?->warn("Category not found for slug: {$entry['category_slug']}");
                continue;
            }

            // Thumbnail
            $thumbPath = null;
            $thumbSrc = "$genDir/{$entry['thumb_jpg']}";
            if (file_exists($thumbSrc)) {
                $thumbName = Str::random(40) . '.jpg';
                Storage::disk('public')->put('thumbnails/' . $thumbName, file_get_contents($thumbSrc));
                $thumbPath = 'thumbnails/' . $thumbName;
            }

            // courses.level is a lowercase enum('beginner','intermediate','advanced')
            // and courses.duration is an int (days) — map the human-readable
            // manifest values onto the real column types/conventions.
            $durationDays = [
                '1 Month' => 30, '2 Months' => 60, '3 Months' => 90,
                '4 Months' => 120, '5 Months' => 150, '6 Months' => 180,
                '8 Months' => 240, '1 Year' => 365,
            ][$entry['duration']] ?? 90;

            $course = Course::create([
                'category_id'       => $category->id,
                'title'             => $entry['title'],
                'slug'              => Str::slug($entry['title']),
                'short_description' => $entry['short_description'],
                'description'       => $entry['description'],
                'price'             => $entry['price'],
                'discount'          => $entry['discount'],
                'level'             => strtolower($entry['level']),
                'duration'          => $durationDays,
                'status'            => 1,
                'thumbnail'         => $thumbPath,
                'delete'            => 1,
            ]);
            $coursesCreated++;

            foreach ($entry['subjects'] as $subjectIndex => $subjectData) {
                $subject = CourseSubject::create([
                    'course_id'  => $course->id,
                    'name'       => $subjectData['name'],
                    'sort_order' => $subjectIndex,
                    'delete'     => 1,
                ]);
                $subjectsCreated++;

                foreach ($subjectData['chapters'] as $chapter) {
                    $pdfSrc = "$genDir/{$chapter['pdf_file']}";
                    if (!file_exists($pdfSrc)) {
                        $this->command?->warn("Missing PDF: {$chapter['pdf_file']}");
                        continue;
                    }

                    $pdfName = Str::random(40) . '.pdf';
                    Storage::disk('public')->put('course_notes/' . $pdfName, file_get_contents($pdfSrc));

                    CourseNote::create([
                        'course_id'        => $course->id,
                        'subject_id'       => $subject->id,
                        'title'            => $chapter['title'],
                        'description'      => $chapter['description'],
                        'file_path'        => 'course_notes/' . $pdfName,
                        'file_size'        => filesize($pdfSrc),
                        'page_count'       => null,
                        'is_downloadable'  => true,
                        'status'           => 1,
                        'download_count'   => 0,
                        'version'          => '1.0',
                        'visibility'       => 'free',
                        'delete'           => 1,
                    ]);
                    $chaptersCreated++;
                }
            }
        }

        $this->command?->info("Created $coursesCreated courses, $subjectsCreated subjects, $chaptersCreated chapters.");
    }
}
