<?php

// Presentation copy only; existing resource and form logic stays in its views.
return [
    'home' => [
        'label' => 'Start Your Journey',
        'title' => 'Build your understanding of law, one topic at a time.',
        'image' => 'courses',
        'alt' => 'Law students discussing a reference book in a library.',
        'body' => 'Explore courses, Bare Acts, Rules and study notes from one place. Choose a subject that interests you and connect your reading with the wider legal context.',
        'detail' => 'Whether you are beginning your studies or revisiting a difficult topic, use the collections below to plan your next step.',
        'action' => 'Explore learning resources',
        'target' => '#courses',
        'points' => ['Learn the foundations', 'Read and revise', 'Explore legal topics'],
    ],
    'acts' => [
        'label' => 'Bare Acts',
        'title' => 'Start with the words of the law.',
        'image' => 'acts',
        'alt' => 'Open statute book and brass scales on a library desk.',
        'body' => 'Build a strong foundation by reading the provisions themselves. Browse the Bare Acts collection by category and use keyword search to find a topic you want to study.',
        'detail' => 'Keep related provisions together as you read, then return to your notes to connect the text with the concepts you are learning.',
        'action' => 'Browse Bare Acts',
        'target' => '#acts',
        'points' => ['Browse by category', 'Search by keyword', 'Read available PDFs'],
    ],
    'rules' => [
        'label' => 'Rules & Regulations',
        'title' => 'Explore the detail behind legal provisions.',
        'image' => 'rules',
        'alt' => 'Indexed legal reference binder beside law books.',
        'body' => 'Rules are an important part of understanding how a legal framework works. Explore the available collection and bring more structure to your reading.',
        'detail' => 'Choose a category or search for a topic below to find the resources that fit your study session.',
        'action' => 'Explore Rules',
        'target' => '#rules',
        'points' => ['Organized categories', 'Focused reading', 'Reference material'],
    ],
    'copys' => [
        'label' => 'Free Study Notes',
        'title' => 'Make room for a clearer revision routine.',
        'image' => 'notes',
        'alt' => 'Revision notebook, tabs and textbook arranged on a study desk.',
        'body' => 'Use the free notes collection to revisit subjects, organize key ideas and support your regular reading. Start with a topic you want to understand more clearly.',
        'detail' => 'Browse by category or keyword, then open the available notes alongside your textbooks and Bare Acts.',
        'action' => 'Find study notes',
        'target' => '#notes',
        'points' => ['Topic-based reading', 'Revision support', 'Free learning resources'],
    ],
    'govtexams' => [
        'label' => 'Examination Preparation',
        'title' => 'Give every study session a purpose.',
        'image' => 'exams',
        'alt' => 'Practice answer sheet, pencil and clock on an examination study desk.',
        'body' => 'Explore study material for Centre and State government examinations. Use the available categories to focus on the subjects that matter to your preparation.',
        'detail' => 'Bring together reading, note-taking and regular revision as you work through the resources below.',
        'action' => 'Explore exam material',
        'target' => '#exams',
        'points' => ['Subject-wise resources', 'Focused preparation', 'Regular revision'],
    ],
    'course' => [
        'label' => 'Law Courses',
        'title' => 'Find a course that fits your learning goals.',
        'image' => 'courses',
        'alt' => 'Two law students discussing an open textbook in a library.',
        'body' => 'Explore the course collection for legal and professional studies. Browse the categories to find subjects that match your interests and the stage of your learning journey.',
        'detail' => 'Review the available course details and use the inquiry options when you need more information before taking the next step.',
        'action' => 'Browse courses',
        'target' => '#courses',
        'points' => ['Explore subjects', 'Review course details', 'Plan your next step'],
    ],
    'legalknowledgelibrary' => [
        'label' => 'Legal Knowledge Library',
        'title' => 'Connect legal concepts with everyday questions.',
        'image' => 'library',
        'alt' => 'Sunlit law library with reference books and a reading table.',
        'body' => 'Explore guides and reading material across the legal topics available in our library. Use the collection to broaden your understanding and discover areas for further study.',
        'detail' => 'Browse a category or search for a specific subject to find the available PDFs below.',
        'action' => 'Explore the library',
        'target' => '#library',
        'points' => ['Discover legal topics', 'Browse the collection', 'Continue your reading'],
    ],
    'legal-knowledge' => [
        'label' => 'Legal Knowledge Inquiry',
        'title' => 'Turn your curiosity into a useful question.',
        'image' => 'inquiry',
        'alt' => 'Illustrative scene of a law student discussing a book with an educator.',
        'body' => 'Looking for information about a particular legal topic? Tell us what you would like to learn and where you need more clarity.',
        'detail' => 'Use the inquiry form below to choose a topic and share your question with the Law Students team.',
        'action' => 'Send an inquiry',
        'target' => '#inquiry',
        'points' => ['Choose your topic', 'Describe your question', 'Share your learning needs'],
    ],
    'contact' => [
        'label' => 'Get in Touch',
        'title' => 'Let us help you find your next step.',
        'image' => 'contact',
        'alt' => 'Headset, laptop and notebook beside law books.',
        'body' => 'Have a question about courses, study resources or using the platform? Get in touch with the Law Students team using the contact details or form below.',
        'detail' => 'Include the subject or resource you are interested in so your message gives us the context we need to help.',
        'action' => 'View contact options',
        'target' => '#contact',
        'points' => ['Course inquiries', 'Resource questions', 'Platform support'],
    ],
    'clientele' => [
        'label' => 'Our Learning Community',
        'title' => 'Different backgrounds. A shared interest in law.',
        'image' => 'community',
        'alt' => 'Illustrative scene of three law students exchanging ideas in a library.',
        'body' => 'Legal learning brings together students, examination aspirants and working professionals. Explore the client and learner information shared on this page.',
        'detail' => 'Use the form below to tell us about your interests and the programme you would like to explore.',
        'action' => 'Explore our community',
        'target' => '#client',
        'points' => ['Students and aspirants', 'Professional learning', 'Shared curiosity'],
    ],
    'gallery' => [
        'label' => 'Learning in Focus',
        'title' => 'Explore the moments behind the learning.',
        'image' => 'gallery',
        'alt' => 'Illustrative still life of a camera and photographs of library interiors.',
        'body' => 'Browse the gallery albums to explore photographs shared by Law Students. Each collection brings together images from a particular group or activity.',
        'detail' => 'Open an album below to look through the available photographs.',
        'action' => 'View gallery albums',
        'target' => '#gallery',
        'points' => ['Browse albums', 'Open photographs', 'Explore collections'],
    ],
    'privacy' => [
        'label' => 'Privacy Policy',
        'title' => 'Understand how your information is handled.',
        'image' => 'privacy',
        'alt' => 'Brass padlock on a closed document folder beside a laptop.',
        'body' => 'Read the privacy policy below for information about personal data and your use of the Law Students platform.',
        'detail' => 'Review the full policy and contact the team if you have a question about its contents.',
        'action' => 'Read the privacy policy',
        'target' => '#site-info',
        'points' => [],
    ],
    'terms' => [
        'label' => 'Terms & Conditions',
        'title' => 'Know the terms before you begin.',
        'image' => 'terms',
        'alt' => 'Agreement and fountain pen arranged beside law books.',
        'body' => 'Take time to read the terms and conditions for using Law Students and its services.',
        'detail' => 'The full document below sets out the applicable terms. Refer to it when you need to understand the conditions of using the platform.',
        'action' => 'Read the terms',
        'target' => '#site-info',
        'points' => [],
    ],
    'disclaimer' => [
        'label' => 'Disclaimer',
        'title' => 'Read with a clear understanding of the context.',
        'image' => 'disclaimer',
        'alt' => 'Magnifying glass resting beside an open legal reference book.',
        'body' => 'Review the disclaimer to understand the context and limitations of the material shared on Law Students.',
        'detail' => 'Read the complete statement below before relying on information from the platform.',
        'action' => 'Read the disclaimer',
        'target' => '#site-info',
        'points' => [],
    ],
    'refund' => [
        'label' => 'Refund Policy',
        'title' => 'Review the policy for payment-related questions.',
        'image' => 'refund',
        'alt' => 'Calculator and receipt folder arranged beside law books.',
        'body' => 'Read the refund policy below when you need information about refund requests and the conditions that apply.',
        'detail' => 'Refer to the full policy for details, and contact the team if you need clarification about your situation.',
        'action' => 'Read the refund policy',
        'target' => '#site-info',
        'points' => [],
    ],
    'sitemap' => [
        'label' => 'Find Your Way',
        'title' => 'Your guide to the Law Students website.',
        'image' => 'sitemap',
        'alt' => 'Library index cards organized beside reference books.',
        'body' => 'Find direct links to the main sections of the website, from courses and study resources to contact information and site policies.',
        'detail' => 'Choose a section below to continue exploring.',
        'action' => 'Explore the sitemap',
        'target' => '#site-info',
        'points' => ['Learning resources', 'Help and information', 'Useful links'],
    ],
    'announcements' => [
        'label' => 'Latest Additions',
        'title' => 'Keep up with new learning resources.',
        'image' => 'announcements',
        'alt' => 'Notebook and fresh reference documents on a library desk.',
        'body' => 'Explore the latest additions to Law Students, including Bare Acts, Rules, free notes, examination material and legal knowledge resources.',
        'detail' => 'The list below links to the relevant collections so you can continue reading in the area that interests you.',
        'action' => 'See latest additions',
        'target' => '#site-info',
        'points' => ['New resources', 'Recent additions', 'More to explore'],
    ],
];
